@hostname=localhost
@port=3000

###
# Returns the application version.
GET http://{{hostname}}:{{port}}/

###
# Returns a list of adjustment types.
GET http://{{hostname}}:{{port}}/adjustment-types


###
# Creates a new adjustment type.
POST http://{{hostname}}:{{port}}/adjustment-types
Content-Type: application/json

{
  "description": "Cleaned room",
  "adjustment": 2
}

###
# Retrieves a single adjustment type.
GET http://{{hostname}}:{{port}}/adjustment-types/1

###
# Deletes an adjustment type.
DELETE http://{{hostname}}:{{port}}/adjustment-types/8

###
# Lists available adjustments.
GET http://{{hostname}}:{{port}}/adjustments

###
# Lists available adjustments of type 1, limited to 10 results.
GET http://{{hostname}}:{{port}}/adjustments?type=1&limit=10

###
# Lists available adjustments since 2015-01-01.
GET http://{{hostname}}:{{port}}/adjustments?since=2023-11-21T00:00:00

###
# Creates a new adjustment.
POST http://{{hostname}}:{{port}}/adjustments
Content-Type: application/json

{
  "type": 1,
  "description": "Mathematics"
}

###
# Retrieves a single adjustment.
GET http://{{hostname}}:{{port}}/adjustments/1

###
# Deletes the adjustment with id 1.
DELETE http://{{hostname}}:{{port}}/adjustments/1

###
# Retrieves the current adjusted time.
GET http://{{hostname}}:{{port}}/time

###
# Lists available time entries.
GET http://{{hostname}}:{{port}}/time-entries

###
# Creates a new time entry.
POST http://{{hostname}}:{{port}}/time-entries
Content-Type: application/json

{
  "time": 120
}

###
# Retrieves a single time entry.
GET http://{{hostname}}:{{port}}/time-entries/1

###
# Deletes a time entry.
DELETE http://{{hostname}}:{{port}}/time-entries/1
